-- comment Database


INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('great man',26,6);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('looking greate bhai',12,17);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('nice place keep enjoying',29,15);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('great bhai meetu soon ',49,21);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('aag lga di bhai',37,34);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('briallant keep working',3,34);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('soon will join you all',86,21);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('nice man !! loved it',81,28);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('bawnadar aayega abb ',83,48);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('boht tezz ho rhe ho ',38,23);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('bade acche ho beta',92,27);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('rakh neeche rakh teri toh',83,7);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('kaise ho bro',5,50);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('aag lga di h bss fire extinguisher bulana pdega',42,4);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('ek kahani h jo sabko sunnani h jakne wako ki toh rooh bhi jaalani h',59,25);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('mast h bhai , mill tabb btata hu kon mast h ',62,31);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('sahi lgg rha h bss ',27,8);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('I think this is the best I’ve seen till now.',83,36);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES (' Not enough for me, you are everything.',34,13);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES (' Just when I couldn’t love you more. You posted this pic and my jaw dropped to the floor.',81,46);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You are a symbol of beauty.',77,38);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES (' Surely you are the most beautiful woman alive, the most that I’ve seen.',96,19);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You mean the world to me.',58,10);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('The word pretty is worthless without you.',64,44);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You are the definition of Beauty',81,4);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Flawless outstanding eccentric lovely beauty.',36,20);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('The stars, the moon, and the sun are minor to me since you sparkle brighter than all of them.',45,25);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You are graceful.',21,47);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES (' Surely you would have been arrested if looking immensely beautiful was a crime.',3,46);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You’re an incredibly stunning, a really pretty, beautiful woman.',51,39);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES (' I guess this is your best look, you look beautiful in this outfit.',37,47);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You look mesmerizing.',68,22);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('I wonder how cute you would be looking when you sleep.',6,35);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You are so much lovely.',29,47);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('I love your curly hair.',2,14);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Your dressing sense is appreciable.',39,41);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES (' You are the sweetest girl I have ever seen.',40,33);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('. I love that straight hair of yours.',79,29);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You are pleasing.',45,35);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Just ‘WOW’ for your natural beauty.',41,33);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You are cute.',18,49);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('I love how comfortable you are in your world.',45,14);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You are very much adorable.',39,5);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You look even more pretty without makeup.',47,45);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('I feel so happy to be with you.',85,13);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You are my safest place.',51,35);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You look beautiful in that dress.',99,15);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('. I wish I had your makeup.',5,23);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You are stunning.',78,14);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('. That natural beauty tho.',25,14);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You have the most beautiful, sparkling eyes.',86,46);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You have the most beautiful smile.',70,10);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('. Your sense of fashion is great.',70,22);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES (' I like your hair.',25,32);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('. You look more beautiful than in the photo.',24,25);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES (' You look stunning.',94,15);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You’re classy.',89,34);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES (' You’re very trendy',100,1);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Landscape/Scenery:',75,40);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Great shot!',82,29);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Nice shot!!',93,6);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Love the view.',74,31);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Did you have fun up there?',46,11);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Selfie/picture of themselves:',13,25);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Looking good!',31,7);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Pretty/beautiful!',57,44);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Handsome!',58,39);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('OH MAH GOSH!!',35,7);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('?????? (three heart-eyed emojis)',20,43);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Sexy pose of themselves:',98,31);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('MESSY!',84,36);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('OMG!',29,42);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('OMG! Be my wife or dad already!!',100,35);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Hot',3,7);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('?????? (three heart-eyed emojis)',44,7);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Wtf, how are you so pretty/handsome?',42,19);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Wow!! In love!!',32,19);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Classic',59,6);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Picture of their outfit or OOTD (outfit of the day):',99,9);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Ou la la',25,32);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Gorgeous!!',12,25);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Love your outfit!!',71,1);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Looking good, man.',2,33);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('A picture of their pet/pets:',26,20);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Soooooo cute!!',48,44);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('cute!',18,25);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('lovely pet you got there!',22,25);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('An inspirational quote:',36,48);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Inspired! Thanks for the share.',66,12);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Needed that, thanks!',11,35);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('I agree/disagree.',13,21);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Inspirational',94,13);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('A picture of their family or children:',28,26);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Lovely children.',29,20);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Adorable kids, you got there!',76,20);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('They will grow up so fast!',6,23);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('I remember when they were X small!! Time flies by to fast!',80,24);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('A picture of their meal:',27,18);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Looks delish! Did you cook that?!?',5,30);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Yummy in my tummy. Yum!',87,15);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Enjoy!!',18,16);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('??????(the drooling mouth emoji)',73,5);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Death of a loved one:',30,31);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Sorry for your loss. My condolences go to you and your family.',26,37);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Rip (person’s name).',80,49);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Sorry for your loss, friend. If you need to talk, I’m always there for you.',48,43);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('My condolences.',56,5);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Anniversary:',66,50);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Congrats!',92,15);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Congratulations on your X years of marriage/engagement!!',86,49);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Woo!! Congrats newlywed!',26,44);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('I’m so happy for you.',16,24);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Great shot!!',60,18);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Clean shot!!',53,26);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Crisp shot man.',88,11);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('I love the aesthetics of this picture.',39,13);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('The bookeh is dope',52,26);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Great tones man',72,41);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('This one is classic',83,25);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('This one is fire',39,3);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('great concepts.',58,40);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Beautiful picture, love the colors.',30,13);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Woow!! Hands down!!',45,27);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('This is purely magic.',18,36);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Your content is amazing.',19,6);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Nice shot… etc etc :)',21,29);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Your beauty is irresistible!!',49,25);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You look energetic.',13,14);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Impressive picture.',100,20);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You look strong and confident.',95,49);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('This picture is lit!!',20,9);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Adorable picture.',59,45);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Your smile makes me Happy.',5,39);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Looking Gorgeous .',83,43);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('This picture made my day.',59,45);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Your beauty has no boundaries.',3,12);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('My word can’t describe your beauty!!',67,22);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ("Your eyes sparkle like something I've never seen before.",27,8);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Handsome hunk',35,15);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('That beard tho (if you go in for details)',86,50);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ("That's dope",69,39);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Nailed it',62,48);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('My squad',69,19);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('High af',67,11);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Awesome',4,40);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Bromantic',42,11);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Hero',33,15);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('This boy is mine',94,18);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('My man',93,36);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('I own this male',49,8);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('He + me = forever',7,18);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You mean the world to me',85,42);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Cant get my eyes off',16,26);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('In nature, light creates the color. In the picture, color creates the light.',44,41);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('NICE GREAT',60,47);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('The beauty has no boundaries in this picture.',43,9);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('SUPER ',23,31);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Your beauty is irresistible.',71,43);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('ADORABLE CHILL LIFE',83,30);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Such a charming picture.',11,40);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('CHAL BE HERO',96,39);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Elegant picture.',30,42);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('NICE PLACE AND WATVH',41,47);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('My words are less to describe this picture.',49,32);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('FDSAFDS',22,1);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Beauty lies within for those who choose to see.',33,48);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('BASDHIYAYY',3,18);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('The power of beauty lies within the soul.',29,6);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('KICKASS LOKK!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!',15,23);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('This picture is worth a thousand words.',41,47);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('GREAT TO SEE U ALIVE ',8,33);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Beauty is power; a smile is its sword.',1,24);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('MSRJAA AJJJRJKLFDSA',68,41);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('This place looks exotic.',2,46);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('DUBAI IS SLIVWE',61,36);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('I love how vibrant colors are in the picture.',10,18);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('GOOOD DATYYYYYYYYYYYYYYYYYYYYYYYYYYYYY',38,20);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Such a scenic view ,looks great.',64,49);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('WONDERFUL IMORESSIVE',69,16);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Impressive picture.',4,28);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('AAGT LGADI BHAI MAJA AA GYA ',78,39);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Adorable picture and Your smile makes me Happy.',42,30);
INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('such a nice cute humbke kind gentke face',1,1);
 INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Looking Gorgeous and This picture made my day. ', 61,1);
 INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ("Never seen a selfie of yours that I don't like. ", 29,48);
 INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You are the coolest. ', 97,27);
 INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You are the coolest. ', 69,19);
 INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You are the coolest. ', 25,15);
 INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You are the coolest. ', 66,23);
 INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Friends forever. ', 6,5);
 INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('They say love is beautiful, but I say friendship is better. ', 13,9);
 INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('AAGT LGADI BHAI MAJA AA GYA  ', 26,32);
 INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('Impressive picture. ', 72,39);
 INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('MSRJAA AJJJRJKLFDSA ', 23,31);
 INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('COOL PIC ', 58,4);
 INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('You are the coolest. ', 68,34);
 INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('xing of public record ', 93,48);
 INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('GREAT JOB ', 10,6);
 INSERT INTO COMMENTS(comment_text ,post_id,user_id) VALUES ('GOOOD DAY !!!!!!!!!!!!!!!!!!!! ', 98,46);


