-- HASHTAGS DATABASE 

INSERT INTO HASHTAGS(hashtag_name) VALUES (' #joinbtsarmy');
INSERT INTO HASHTAGS(hashtag_name) VALUES (' #kisaansupport');
INSERT INTO HASHTAGS(hashtag_name) VALUES (' #fitnessfreak');
INSERT INTO HASHTAGS(hashtag_name) VALUES (' #runforunity');
INSERT INTO HASHTAGS(hashtag_name) VALUES (' #studentlivesmatter');
INSERT INTO HASHTAGS(hashtag_name) VALUES (' #cancellJEEiit');
INSERT INTO HASHTAGS(hashtag_name) VALUES (' #REOPEN colleges');
INSERT INTO HASHTAGS(hashtag_name) VALUES (' #party');
INSERT INTO HASHTAGS(hashtag_name) VALUES (' #followme');
INSERT INTO HASHTAGS(hashtag_name) VALUES (' #christmas');
INSERT INTO HASHTAGS(hashtag_name) VALUES (' #socialmedia');
INSERT INTO HASHTAGS(hashtag_name) VALUES (' #family');
INSERT INTO HASHTAGS(hashtag_name) VALUES (' #festivesale');
INSERT INTO HASHTAGS(hashtag_name) VALUES (' #sunnyday');
INSERT INTO HASHTAGS(hashtag_name) VALUES (' #enjoy');
INSERT INTO HASHTAGS(hashtag_name) VALUES (' #weekendmasti');
INSERT INTO HASHTAGS(hashtag_name) VALUES (' #love');
INSERT INTO HASHTAGS(hashtag_name) VALUES ('  #instagood');
INSERT INTO HASHTAGS(hashtag_name) VALUES (' #photooftheday');
INSERT INTO HASHTAGS(hashtag_name) VALUES ('  #beautiful');
INSERT INTO HASHTAGS(hashtag_name) VALUES (' #fashion');
INSERT INTO HASHTAGS(hashtag_name) VALUES ('  #tbt');
INSERT INTO HASHTAGS(hashtag_name) VALUES (' #happy');
INSERT INTO HASHTAGS(hashtag_name) VALUES (' #cute');
INSERT INTO HASHTAGS(hashtag_name) VALUES ('  #followme');
INSERT INTO HASHTAGS(hashtag_name) VALUES ('  #like4like');
INSERT INTO HASHTAGS(hashtag_name) VALUES ('  #follow');
INSERT INTO HASHTAGS(hashtag_name) VALUES ('  #me');
INSERT INTO HASHTAGS(hashtag_name) VALUES ('  #picoftheday');
INSERT INTO HASHTAGS(hashtag_name) VALUES (' #selfie');
INSERT INTO HASHTAGS(hashtag_name) VALUES ('#GOGREEN ');
