-- post_database
insert into post (photo_id,video_id,user_id,caption,location) values
(66,50,18,'HEY!!','VHA JHA KOI AATA JAATA NI'),
(87,64,9,'Live a good story.','The Red Fort, Delhi.'),
(80,22,3,'Escape the ordinary.','The Taj Mahal, Agra.'),
(9,65,48,'The best is yet to come.','Pangong Lake, Ladakh.'),
(20,86,19,'These are days we live for.','Valley of Flowers, Nainital.'),
(5,65,12,'Life happens, coffee helps.','Jaisalmer Fort, Jaisalmer.'),
(61,59,33,'Short sassy cute & classy.','Ruins of Hampi, Karnataka.'),
(94,99,45,'The future is bright.','Ghats at Varanasi, Uttar Pradesh.'),
(38,83,50,'Namastay in bed.','Backwaters, Kerala.'),
(9,89,1,'I have more issues than vogue.','abhayapuri'),
(61,10,6,'Life is short. Smile while you still have teeth.','achabbal'),
(23,21,19,'Ah, a perfectly captured selfie!','achalpur'),
(40,57,16,'Let’s just be who we are.','achhnera'),
(38,62,18,'One bad chapter doesn’t me','adari'),
(81,23,29,'Cinderella never asked for a prince.','adalaj'),
(9,65,23,'A selfie is worth a thousand words.','adilabad'),
(72,14,24,'Born to stand out with selfies.','adityana'),
(34,33,49,'I’m sorry I exist, here, a selfie.','pereyaapatna'),
(89,14,15,'….','adoni'),
(27,72,3,'dfgfsggf','adoor'),
(27,24,33,'4545','adyar'),
(75,24,8,'007@','adra'),
(33,88,25,',,,,','afzalpura'),
(94,99,31,'…..','agartala'),
(30,14,31,';;;@','agra'),
(72,4,46,'.','ahiwara'),
(25,38,1,'…','ahmedabad'),
(88,14,34,'….....','ahmedgarh'),
(23,64,31,'…..','ahmednagar'),
(51,45,11,'.///','ahmedpur'),
(48,16,50,'???/','aizawl'),
(36,49,32,'//""//','ajmer'),
(10,65,30,'Selfie on fleek.','ajra'),
(25,57,6,'This is how to become a heart breaker.','akaltara'),
(37,16,26,'No guts, no story.','akathiyoor'),
(95,48,32,'The selfie is the worst judge of beauty.','akhnoor'),
(80,7,7,'Nobody’s perfect…but I’m close.','akkalkot'),
(22,94,34,'Does this selfie make me look fat?','akola'),
(91,56,6,'Rate this selfie from 1-10.','akot'),
(100,19,11,'But first… let me take a selfie.','alandha'),
(35,25,41,'Gracing your feed with this fabulous selfie.','alandi'),
(34,22,9,'Mirror: “You look cute today.” Camera: “LOL, no.”','alang'),
(62,62,36,'Life is like a mirror, we get the best results when we smile.','alappuzha'),
(80,42,24,'Smile at the world, and she’ll smile back.','aldona'),
(4,46,16,'Keep the Smile On!','alibag'),
(96,9,39,'Please don’t download my Selfie, you may fall in love with me.','aligarh'),
(50,63,43,'Silly girls are the best.','alipurduar'),
(50,30,36,'I am not a selfie expert.','allahabad'),
(57,25,13,'Life is better when you’re smiling.','almora'),
(79,72,31,'I don’t take selfies all the time, just every day.','aalanavara'),
(37,49,39,'Be the best version of yourself.','along'),
(49,88,41,'Beauty begins the moment you decide to be yourself.','alur'),
(59,59,32,'Do more of what makes you happy.','assam'),
(89,24,3,'Anti-You.','jammu and kashmir'),
(10,25,15,'Sometimes I’m in a selfie mood.','maharashtra'),
(60,18,18,'I am not taking a selfie, I am just checking my camera quality.','maharashtra'),
(80,93,46,'Animal selfies are the best selfies.','uttar pradesh'),
(48,68,1,'Selfie Time!','west bengal'),
(89,35,46,'Simplicity is the key to brilliance.','uttar pradesh'),
(28,6,24,'There is beauty in simplicity.','uttarakhand'),
(31,6,19,'Be obsessively grateful.','karnataka'),
(67,50,3,'May your day feel as good as taking this perfect selfie on the first try.','arunachal pradesh'),
(55,70,21,'I’m not lazy, just relaxed.','maharashtra'),
(41,18,32,'Dinner time is selfie time.','maharashtra'),
(75,29,44,'I must have no selfie control.','karnataka'),
(13,1,38,'All-natural.','maharashtra'),
(5,86,25,'May your day feel as good as taking this perfect selfie on the first try.','gujarat'),
(60,57,32,'My favorite part about this selfie is the invisible crown.','kerala'),
(47,38,25,'Keep calm and take a selfie.','goa'),
(53,7,34,'Some call it arrogant, I call it confidence.','uttar pradesh'),
(87,64,13,'I woke up like this; flawless.','gujarat'),
(3,83,49,'“Who said I was an angel?”','andhra pradesh'),
(69,89,7,'Bout to make me give you a reason to be insecure.','gujarat'),
(80,52,22,'Dress like you’re already famous!','karnataka'),
(8,48,9,'You’re not fully dressed until you sparkle.','andhra pradesh'),
(86,70,3,'Normal is boring for me.','kerala'),
(44,12,1,'I am not trying to be cool, It’s what I am.','karnataka'),
(45,75,38,'I collect smiles, and then I give them away.','west bengal'),
(53,14,38,'A girl should be like a butterfly. Pretty to see, hard to catch.','karnataka'),
(87,96,47,'Queen of own world.','tripura'),
(40,87,2,'Being sexy is about attitude possessed, not a body type. It’s a state of mind.','uttar pradesh'),
(85,26,8,'Sexy is being confident, independent, and having fun.','chhattisgarh'),
(93,51,45,'If you cannot do great things, do small things in a great way.','gujarat'),
(98,17,33,'She turned her can’t into cans & her dreams into plans.','punjab'),
(30,91,35,'Coffee in one hand, Confidence in other.','maharashtra'),
(73,87,46,'Short hair, don’t care.','maharashtra'),
(91,19,12,'Be your own reason to smile.','mizoram'),
(79,45,5,'Seek respect, not attention.','rajasthan'),
(69,60,7,'I dress to impress myself.','maharashtra'),
(71,38,24,'A smile is the best makeup a girl can wear.','chhattisgarh'),
(43,33,50,'She was like a moon, a part of her always stayed hidden.','kerala'),
(10,20,20,'Smile with your eyes.','jammu and kashmir'),
(57,26,35,'Life is too short to wear boring clothes.','maharashtra'),
(8,14,33,'Lift up your head princess, if not the crown falls.','The Red Fort, Delhi.'),
(85,30,32,'Dressing well is the best revenge.','The Taj Mahal, Agra.'),
(27,12,8,'I don’t worry. I don’t doubt it. I’m daring. I’m a rebel.','Pangong Lake, Ladakh.'),
(47,81,10,'Life happens, coffee helps.','Valley of Flowers, Nainital.'),
(49,26,7,'You must be bold, brave, and courageous and find a way… to get in the way.','Jaisalmer Fort, Jaisalmer.'),
(97,12,41,'Don’t stop when you are tired. Stop when you are done!','Ruins of Hampi, Karnataka.'),
(38,40,16,'This is my moment I just feel so alive.','Ghats at Varanasi, Uttar Pradesh.');
