
INSERT INTO users(username, profile_photo_url, bio) VALUES 
("kanavphull","https://pbs.twimg.com/profile_images/1386885117428191232/70SyHOxP_400x400.jpg","Hedonist yet Spiritual || IT at NITJ 2024"),
('raj gupta' , '/klsadf893724:f//432' , 'soon to be updated'),
('Sahib Singh' , 'https://pbs.twimg.com/profile_images/1465003815820693506/gbTJoe66_400x400.jpg' ,"Life is a journey, It drives you MAD.|| IT NITJ'24"),
('Sakshi Warandani' , "" , "NITJ wish me on 23 jan"),
("chhaprinibba", "/sdfvsdf", "Heart Stealer"),
("dettol sharma", "/sdfvsdf", "Dettol Stealer"),
('sunil' , '/yisadf324//' , 'hotel manageemnt '),
('sanjay' , '/fduiahj43' , 'football lover' ),
('Axel Sivert Anker' , '/adaskjnas','Norwegian'),
('Steven','/acdsccsdc', 'living life my way'),
('Jack','https://picsum.photos/100','𝐖𝐞𝐥𝐜𝐨𝐦𝐞 𝐓𝐨 𝐌𝐲 𝐏𝐫𝐨𝐟𝐢𝐥𝐞'),
('Oliver','https://picsum.photos/101','𝐎𝐟𝐟𝐢𝐜𝐢𝐚𝐥 𝐀𝐜𝐜𝐨𝐮𝐧𝐭'),
('James','https://picsum.photos/102','𝐖𝐢𝐬𝐡 𝐌𝐞 𝐎𝐧 𝟑 𝐎𝐜𝐭𝐨𝐛𝐞𝐫'),
('Charlie','https://picsum.photos/103','aap yha aae kisliye'),
('Harris','https://picsum.photos/104','𝐒𝐚𝐧𝐬𝐤𝐚𝐫𝐢 𝐋𝐚𝐝𝐤𝐚'),
('Lewis','https://picsum.photos/105','aapne bulaya isilye'),
('Leo','https://picsum.photos/106','𝐆𝐲𝐦 𝐋ø𝐯è𝐫'),
('Noah','https://picsum.photos/107','aae hai toh kaam bi btiye'),
('Alfie','https://picsum.photos/108','𝐒𝐢𝐧𝐠𝐥𝐞'),
('Rory','https://picsum.photos/109','phle zara aap muskurae'),
('Alexander','https://picsum.photos/110','𝐑𝐞𝐬𝐩𝐞𝐜𝐭 𝐅𝐨𝐫 𝐀𝐥𝐥'),
('Max','https://picsum.photos/111','𝐈𝐧𝐬𝐭𝐚𝐠𝐫𝐚𝐦 𝐊𝐢𝐧𝐠'),
('Logan','https://picsum.photos/112','𝐂𝐚𝐤𝐞 𝐌𝐮𝐫𝐝𝐞𝐫 𝐎𝐧 𝟏𝟕 𝐉𝐮𝐧𝐞'),
('Harry','https://picsum.photos/113','hhddsgb'),
('Theo','https://picsum.photos/114','♥️𝐏𝐡𝐨𝐭𝐨𝐠𝐫𝐚𝐩𝐡𝐲 '),
('Thomas','https://picsum.photos/115','siudgfibsiugs'),
('Brodie','https://picsum.photos/116','𝐌𝐮𝐬𝐢𝐜 𝐀𝐝𝐝𝐢𝐜𝐭'),
('Archie','https://picsum.photos/117','uhiusgfufiusf'),
('Jacob','https://picsum.photos/118',' 𝐒𝐢𝐧𝐠𝐥𝐞 '),
('Finlay','https://picsum.photos/119','usdsgbcu'),
('Finn','https://picsum.photos/120','𝐏𝐫𝐨𝐮𝐝 𝐓𝐨 𝐁𝐞 𝐇𝐢𝐧𝐝𝐮'),
('Daniel','https://picsum.photos/121','hucussgcusn'),
('Joshua','https://picsum.photos/122','𝐁𝐢𝐠 𝐅𝐚𝐧 𝐎𝐟 𝐌𝐚𝐡𝐚𝐤𝐚𝐥'),
('Oscar','https://picsum.photos/123','𝐌𝐫.𝐩𝐞𝐫𝐟𝐞𝐜𝐭'),
('Arthur','https://picsum.photos/124','𝐇𝐚𝐭𝐞 𝐦𝐞 𝐨𝐫 𝐃𝐚𝐭𝐞 𝐦𝐞'),
('Hunter','https://picsum.photos/125','𝐩𝐡𝐨𝐭𝐨𝐡𝐨𝐥𝐢𝐤'),
('Ethan','https://picsum.photos/126','gygyuuy'),
('Mason','https://picsum.photos/127',' 𝐟𝐨𝐨𝐝𝐲 '),
('Harrison','https://picsum.photos/128','gfytfvy'),
('Freddie','https://picsum.photos/129','𝐬𝐢𝐧𝐠𝐥𝐞'),
('Ollie','https://picsum.photos/130','fytfysguf'),
('Adam','https://picsum.photos/131','𝐔 𝐰𝐢𝐥𝐥 𝐟𝐢𝐧𝐝 𝐚 𝐛𝐨𝐲 𝐛𝐞𝐭𝐭𝐞𝐫 𝐭𝐡𝐚𝐧 𝐦𝐞 𝐛𝐮𝐭 𝐔 𝐝𝐨𝐧’𝐭 𝐟𝐢𝐧𝐝 𝐛𝐨𝐲 𝐥𝐢𝐤𝐞 𝐦𝐞'),
('William','https://picsum.photos/132','fyasu'),
('Jaxon','https://picsum.photos/133','𝙊𝙛𝙛𝙞𝙘𝙞𝙖𝙡 𝙖𝙘𝙘𝙤𝙪𝙣𝙩'),
('Aaron','https://picsum.photos/134','ytyftftyi'),
('Cameron','https://picsum.photos/135','uygdghfios'),
('Liam','https://picsum.photos/136','ygyugdysgc'),
('George','https://picsum.photos/137','𝙈𝙪𝙨𝙞𝙘 𝙡𝙤𝙫𝙚𝙧'),
('Jamie','https://picsum.photos/138','ygsgsogt'),
('Callum','https://picsum.photos/139','𝙎𝙥𝙤𝙧𝙩𝙨 𝙡𝙤𝙫𝙚𝙧');

